### ISSUE TITLE
cuid::is_cuid panics on empty strings

### ISSUE THREAD

**Issue by DeppLearning** [mplanchard/cuid-rust#3]
Thanks for the crate. Using it for a while now but encountered this issue today.

Instead of a panic I was expecting the method to return false. If this isn't feasible then maybe document the behavior?

Example:

```
cuid::is_cuid("")
```
-> `panicked at 'byte index 1 is out of bounds of' `

**Comment by mplanchard** [comment]
Thanks for the report! I agree this should return false, and I’m happy to
update it. I’m on vacation this week, but I’ll get to it as soon as
possible

**Comment by mplanchard** [comment]
Resolved with a4fca2f and released in version [1.1.0](https://crates.io/crates/cuid/1.1.0), along with some improvements to the `is_cuid()` and `is_slug()` functions. Thanks again for the report!
