### ISSUE TITLE
Cuid standard is deprecated.

### ISSUE THREAD

**Issue by ericelliott** [mplanchard/cuid-rust#4]
Due to security concerns (which also exist in database auto-increment ids, uuid/guid, and most other id standrads), the Cuid standard is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).

**Comment by ronlobo** [comment]
Just throwing my 2 cents in for making this a new package with all the jazz and buzz.

Thoughts?

**Comment by ronlobo** [comment]
Happy to take it

**Comment by mplanchard** [comment]
My plan is to publish a new package for cuid2, and then to add a `cuid2` function in this package that calls that one (both set up as crates in this workspace).

I've got things mostly complete, but there were a few open questions about how to port some stuff from the JS implementation (see paralleldrive/cuid2#25 and paralleldrive/cuid2#27)

**Comment by mplanchard** [comment]
The [cuid2](https://crates.io/crates/cuid2) crate has been published to crates.io, at version 0.1.0 (not quite ready to commit to API stability yet, but will soon!)

All cuid v1 functions in the `cuid` crate have been marked as deprecated, and a new [`cuid2()`](https://docs.rs/cuid/latest/cuid/fn.cuid2.html) function has been added.
