### ISSUE TITLE
Please dont panic

### ISSUE THREAD

**Issue by numfin** [mplanchard/cuid-rust#6]
Don't use expect/unwrap in your code please. I want to react on errors, not just crash.

**Comment by mplanchard** [comment]
The only `expect` in `cuid2`  that's even theoretically possible is if for some reason your system time is set to before 1970-01-01, in which case this library will be far from the only broken thing. 

Otherwise, all of the conditions are explicitly impossible because of math or things the type system doesn't know, like the fact that `PRIMES` is statically a non-empty array.

If you can find me a reasonable situation in which any of these panics actually happen, I'd be happy to address it.

**Comment by mplanchard** [comment]
Note that as far as I know on POSIX systems it's literally impossible to set your system time to before 1970-01-01, so I think that `.expect()` is also unreachable on those systems. I don't know offhand whether this is also the case on Windows though.

**Comment by mplanchard** [comment]
I added some more comments explaining why I feel these panics are unreachable in dad5887. Please feel free to reopen this issue if you disagree with my reasoning.

**Comment by mplanchard** [comment]
Just circling back to this, I want to be clear about my philosophy regarding panics, in case anyone else finds this issue.

**As a user of the library, you should never see a panic. If you do, it's a bug! Please report it!**

However, I'm not going to avoid using `.expect()` or the [index operator](https://doc.rust-lang.org/std/ops/trait.Index.html) (`[]`) in cases where I have already checked the preconditions and know that they cannot generate a panic. This is especially true in cases where it would make the library interface objectively less performant or more complicated, e.g. returning a `Result` where I know the `Err` state is actually impossible.

The standard library itself uses `.unwrap()` and `.expect()` where appropriate, so if your requirement is that none of the libraries you use ever use unwrap or expect, you'll need to write a lot of things yourself and use `nostd`. 

In general, I am aligned with burntsushi's approach to panics, which he outlined in [this post](https://blog.burntsushi.net/rust-error-handling/#a-brief-interlude-unwrapping-isnt-evil), specifically, panics are acceptable:

> When panicking indicates a bug in the program. When the invariants of your code should prevent a certain case from happening (like, say, popping from an empty stack), then panicking can be permissible. This is because it exposes a bug in your program. This can be explicit, like from an assert! failing, or it could be because your index into an array was out of bounds.

I don't use panics lightly, and again, as a user of the library, **you should never see a panic.**

If you have a problem with this, you can always write a thin wrapper around this library's functions that uses [std::panic::catch_unwind()](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) to ensure that even those panics that should be impossible will never actually cause a panic in calling code. Or, of course, you can fork the library.

**Comment by numfin** [comment]
@mplanchard hi sorry I'm not usually checking notifications on github.
I don't mind having .unwrap() .expect() in unreachable places. But i don't like when library decides to crash my program for some reason (yes my program crashed and this is why i wrote you an issue after i checked slightly your source code). Yes this error is rare, but this is an error and the point of Rust is not "this is rare so you probably not gonna catch it" but "i don't trust humans and this is why i rely on compiler".
I dropped this library after i got this crash and don't remember why and what crash i got.
Again i don't mind if you use expect and unwrap in `main` program, but please avoid panicking in libraries. No one generating trillions of cuids per second and for those "performance" reasons you can just add cfg so people who really need extra performance can trim those errors.
But i want my program to work and not just randomly crash. I hope you understand my point. I understand yours, i just not agree with it
