### ISSUE TITLE
`bigint` dependency is deprecated and apparently unused

### ISSUE THREAD

**Issue by HeavenVolkoff** [mplanchard/cuid-rust#8]
Hey there,

I'm currently working on a project that includes `cuid` as a secondary dependency.

Recently, I started receiving a warning from Clippy:
```sh
$> cargo clippy --fix
    [...]
    Finished dev [unoptimized + debuginfo] target(s) in 1m 11s
warning: the following packages contain code that will be rejected by a future version of Rust: bigint v4.4.3
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
```

After examining my `Cargo.lock` file, it appears that the only crate depending on `bigint` is `cuid`. However, looking into `cuid` code, it seems that `bigint` is not being utilized (I tested removing it and running `cargo test --workspace --all-features --no-run`, and everything compiled successfully).

So, considering `bigint` is [deprecated](https://github.com/paritytech/bigint#deprecated) and apparently unused, would it be possible to remove this crate from the `dependencies` list from `cuid`.

Thanks in advance!

**Comment by mplanchard** [comment]
Done in 94d4cd0, thanks for the report!
