### ISSUE TITLE
cuid2::is_cuid2 for validiting a cuid2 string

### ISSUE THREAD

**Issue by alelopezperez** [mplanchard/cuid-rust#9]
#### Hi, I noticed that `cuid::is_cuid` is now deprecated since it follows non cuid2 standards. I checked the original isCuid2 from paralleldrive implementation and transcribed to a similar function from the deprecrated `cuid::is_cuid`

# Original JS Implementation
#### [link to original JS implementation](https://github.com/paralleldrive/cuid2/blob/main/src/index.js#L103)

```
const isCuid = (id, { minLength = 2, maxLength = bigLength } = {}) => {
  const length = id.length;
  const regex = /^[0-9a-z]+$/;

  try {
    if (
      typeof id === "string" &&
      length >= minLength &&
      length <= maxLength &&
      regex.test(id)
    )
      return true;
  } finally {
  }

  return false;
};
```
#### The requirements are as follows
- length from 2 to 32 (in the code we have a BIG_LENGTH so any changes will reflect on the function.
- it only contains lowecase a to z and 0 to 9

#### Added Requirements by me 
- starts with an lowercase ascii letter ( a to z)

**Comment by mplanchard** [comment]
Sorry for the slow response on this. Just recently finished up moving across the country, so things have been hectic!
